global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: node
    # if your node_exporter has basic auth, uncomment bellow and change user/pass
    # basic_auth:
    #   username: prometheus
    #   password: prometheus
    static_configs:
    - targets: ['localhost:9100']